<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" Version="5.3.0" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DivisionMath">
      <HintPath>..\..\DivisionMath\DivisionMath\bin\Debug\net10.0\DivisionMath.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
